edit eslint config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,5 @@
 #!/bin/sh
 
-# Run ESLint to check for linting errors
-npm run lint
-
-# Check the exit status of the linting command
-if [ $? -ne 0 ]; then
-  # If linting failed, display an error message and prevent the commit
-  echo "Linting failed. Please fix the linting errors before committing."
-  exit 1
-fi
-
 # Run Prettier check to verify code formatting
 npm run prettier:check
 
@@ -17,6 +7,16 @@ npm run prettier:check
 if [ $? -ne 0 ]; then
   # If Prettier check fails, display an error message and prevent the commit
   echo "Prettier check failed. Please format your code before committing, 'npm run prettier'."
+  exit 1
+fi
+
+# Run ESLint to check for linting errors
+npm run lint
+
+# Check the exit status of the linting command
+if [ $? -ne 0 ]; then
+  # If linting failed, display an error message and prevent the commit
+  echo "Linting failed. Please fix the linting errors before committing."
   exit 1
 fi
 
